### ISSUE TITLE
proxied requests get double compressed

### ISSUE THREAD

**Issue by woodsaj** [go-macaron/gzip#2]
we have a use case where requests are conditionally proxied to another service.  That other service will already compress the response, but this middleware is compressing the body a second time.

It seems like this handler should exit early if there is already a "Content-Encoding: gzip" header already set on the response.

**Comment by woodsaj** [comment]
This was harder to address then i initially thought.  Supporting this usecase required a signficant amount of refactoring, so i just created a new middleware handler:  https://github.com/raintank/gziper

I would be happy to submit a PR for this if anyone is interested.

**Comment by unknwon** [comment]
Hi, thanks for the feedback!

I would recommend create a new middleware as you did already. :clap:
